### ISSUE TITLE
Error 255 when running example code

### ISSUE THREAD

**Issue by Manderikoo** [open-rpa/node-red-contrib-tagui#3] opened 2021-07-27 06:54 UTC
Hello, I am experiencing an error when running the TagUI node. Since I am using the example workflow provided on the node's information page, I do not think the issue lies in the connection with the other nodes. Here are some screenshots showing the error I received when injecting into the node.

![image](https://user-images.githubusercontent.com/87259636/127109164-88093cbf-af7c-42bc-8b52-3fdbce8e58af.png)

![image](https://user-images.githubusercontent.com/87259636/127108883-1b15533c-9584-4e5f-b96a-b76f6749c110.png)

For additional information, I am using the local version of OpenIAP's NodeRed on a Windows 10.

**Comment by skadefro** [comment] 2021-07-27 07:20
Unless tagui also has an storage module, this look like an issue with nodered, not tagui or node-red-contrib-tagui.
How did you install and run the nodered ? 
If using openiap's nodered, it will tell nodered to use openiap's storage provider instead of the built in one, so this really sounds like an openiap issue.

**Comment by Manderikoo** [comment] 2021-07-28 08:30
I am using the OpenIAP's nodered like you said. I installed it using NPM onto my windows like the instructions listed on the OpenFlow Github page. The only difference is that I installed noderedlocal instead of noderedremote. Does noderedlocal use openiap's storage provider?

**Comment by skadefro** [comment] 2021-07-28 08:39
And how did you install your local openflow ? docker/npm, from source ?

**Comment by Manderikoo** [comment] 2021-07-28 08:50
Also with NPM if I recall correctly.

**Comment by skadefro** [comment] 2021-07-28 09:01
It would be super helpfull if you started giving more informartion, than simple answers.
What does the log say, is nodered connected, has it registered its queues, does openflow show any issues, did the nodered authenticate successfull etc ?

**Comment by skadefro** [comment] 2021-07-28 09:04
using
```
pm2 logs --lines 100
```
and 
```
pm2 monit
```
can be very helpfull when troubleshooting ( when using monit, then in a seperate commandline restart the services with pm2 restart [id]

**Comment by Manderikoo** [comment] 2021-07-28 09:40
Sorry for being so brief, I have a surface level understanding of the everything involved, so I am not always sure how to get the information needed, but I will try my best where I can. 

Here is what I get then I run the commands on the command line:
![image](https://user-images.githubusercontent.com/87259636/127300388-d0ac74e3-622f-4cbc-ae9b-b811377d4eee.png)

The same error also occurs when I run pm2 restart

**Comment by skadefro** [comment] 2021-07-28 09:46
when starting cmd, make sure to use "run as administrator". A normal user is not allowed to connect to the namepipe pm2 is listening on, on windows.

**Comment by Manderikoo** [comment] 2021-07-28 09:55
Sorry for being brief, I have a shallow understanding of everything involved, so I don't know how to obtain or identify information that would be helpful. That being said, I will try my best nonetheless.

Also, yes, I just realized that I was not running as administrator, hence why I deleted the previous reply. haha

Here's the result from the logs after running pm2 restart:
![image](https://user-images.githubusercontent.com/87259636/127302431-4ccdf6e0-a966-4ece-898e-1d3492990517.png)
And the dashboard from pm2 monit:
![image](https://user-images.githubusercontent.com/87259636/127302599-5611c539-5143-4bf1-8ef9-1f0d12978b34.png)
and the info provided by the command line after running the restart command:
![image](https://user-images.githubusercontent.com/87259636/127302929-bf2d12da-5fc2-4b1f-983a-2c431a00dfb9.png)

Also it seems like at least the tagui logo has returned after the restart.
![image](https://user-images.githubusercontent.com/87259636/127302783-c08574b4-51d7-4f13-9dcb-46a5b12eb436.png)

**Comment by skadefro** [comment] 2021-07-28 09:59
The "cut" is weird .... do you have any idear where that could come from ?
as far as i can remember the only place where nodered is executing something, is when installing npm packages doing start up.
is there some special charecters in the path to where nodered configs are placed ? ( where did you place the .env files )

**Comment by Manderikoo** [comment] 2021-07-28 10:06
No.. I don't recall using or seeing "cut" anywhere for anything in OpenAPI or TagUI, and I think my nodered configs are placed in a pretty standard location:
![image](https://user-images.githubusercontent.com/87259636/127304416-85059308-f867-4e3c-a059-cfa7a46f734f.png)

**Comment by skadefro** [comment] 2021-07-28 10:08
That is strange .... what about your user profile ? Does that contain something including "cut" ?
Maybe its the tagui module that is trying to execute something ( for instance when setting permissions ) that "trips" it.

**Comment by skadefro** [comment] 2021-07-28 10:09
oohh, wait ... That's it ...

**Comment by skadefro** [comment] 2021-07-28 10:11
could you stop nodered ( pm2 stop 1 ) 
and then from a NORMAL cmd, not the admin one, run this command, go to c:\openflow and run
openflow-nodered-cli --run noderedlocal

**Comment by Manderikoo** [comment] 2021-07-28 10:18
Okay, here's what I have so far. Not sure if its still running because it's stalling at the last line. 

![image](https://user-images.githubusercontent.com/87259636/127306196-216bb7f5-548f-46a5-a4eb-cec6a3228e7f.png)

**Comment by skadefro** [comment] 2021-07-28 10:22
I see "nlp" .. could it be, that module is triggering something that could end up with the "cut" error ? ( i don't know that module )
anyway, try re-adding the missing modules and keep an eye on the console and see what happens :-)

**Comment by Manderikoo** [comment] 2021-07-28 10:36
Okay, I have reinstalled all the missing modules (tagui, image output and nlp), and here is what I got:

![image](https://user-images.githubusercontent.com/87259636/127308543-634cb057-2262-4c55-92b2-0a533ef249ef.png)
![image](https://user-images.githubusercontent.com/87259636/127308582-06e3725f-4bb7-4404-9000-9df0931aba18.png)

**Comment by Manderikoo** [comment] 2021-07-28 10:37
Here is what I get after trying to inject into the tagui node again:
![image](https://user-images.githubusercontent.com/87259636/127308700-21780408-ddd1-40af-bc64-b0bbd0f9c962.png)
![image](https://user-images.githubusercontent.com/87259636/127308738-295c6a3e-648a-400d-be1e-7008773c934e.png)
![image](https://user-images.githubusercontent.com/87259636/127308781-7784ed45-2dca-4395-a1e3-a1da66c46be4.png)

**Comment by skadefro** [comment] 2021-07-28 10:37
Perfect, and does the tagui node work now ? if not, is there any errors in the console ?

**Comment by skadefro** [comment] 2021-07-28 10:39
Ah, ok, you just added an error ....
That part is abit out of my compentancy, i need @kensoh for that one ( see the first image in the latest message )

**Comment by kensoh** [comment] 2021-07-28 12:59
Hi Guys, adding my inputs -

1. cut is used by TagUI and it is packaged together with the TagUI_Windows.zip under tagui\src\unx folder. However, perhaps anti-virus software or other reasons it might be removed? (assuming the cut error message if from TagUI process)

2. TagUI has a npm module at https://www.npmjs.com/package/tagui but it is obsolete already, not sure if you tried to install it. Don't install that. The Node-RED TagUI module that Allan has created will take care of downloading and installing TagUI

3. If it is the error message here - https://github.com/open-rpa/node-red-contrib-tagui/issues/3#issuecomment-888205661 it looks like the npm anzip module is missing in the Node-RED TagUI module at this line - https://github.com/open-rpa/node-red-contrib-tagui/blob/main/src/tagui.ts#L34

For me when I install the Node-Red TagUI module it works like a breeze.

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/tagui">tagui</a></strong></div><div>Command-line tool for digital process automation (RPA)</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/6a9f7d7b8b4aae2b202a82eb51efcbec5a0df01d55071331aa92ab45a4511192/open-rpa/node-red-contrib-tagui" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/open-rpa/node-red-contrib-tagui">node-red-contrib-tagui/tagui.ts at main · open-rpa/node-red-contrib-tagui</a></strong></div><div>Contribute to open-rpa/node-red-contrib-tagui development by creating an account on GitHub.</div></blockquote>

**Comment by kensoh** [comment] 2021-07-29 08:42
Hi Allan, adding on to above, we found the root cause of the 'cut' error.

It looks like in below line, you define the URL to download for Windows. However, in the the if-else statement right after, there is only a check for darwin (macOS), and else everything falls under Linux. I think that's why on Amanda's laptop the Linux version is installed. For Linux version of TagUI, I didn't package in the tagui\src\unx files which are Windows versions of those Linux commands used by TagUI.

https://github.com/open-rpa/node-red-contrib-tagui/blob/main/src/tagui.ts#L57

Another data point to add on is, after Amanda try to install the missing anzip module and restarted the application using pm2, the 255 error with 'cut' is not recognised error comes back.

<blockquote><img src="https://opengraph.githubassets.com/6a9f7d7b8b4aae2b202a82eb51efcbec5a0df01d55071331aa92ab45a4511192/open-rpa/node-red-contrib-tagui" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/open-rpa/node-red-contrib-tagui">node-red-contrib-tagui/tagui.ts at main · open-rpa/node-red-contrib-tagui</a></strong></div><div>Contribute to open-rpa/node-red-contrib-tagui development by creating an account on GitHub.</div></blockquote>

**Comment by kensoh** [comment] 2021-07-29 08:49
Adding on, in my Zoom Q&A call with Amanda, I made a copy of her local working TagUI installation to the folder where the Node-RED module is looking for --> %userprofile%\tagui directory. And it works now 🎉

**Comment by skadefro** [comment] 2021-07-30 09:52
Thank you for pointing out the issue with platform check. I have pushed a fix and updated on npm and on flows.nodered.org
Can we close the issue now or is there still issues ? ( sounds like it has been fixed ? )

**Comment by kensoh** [comment] 2021-07-30 12:08
Oh yes of course, your fix will download the right TagUI_Windows.zip and there shouldn't be issue anymore. Yesterday, we replaced the tagui folder used by Node-RED TagUI with the TagUI_Windows.zip and there's no more error. Thank you Allan!

(please close the issue, or Amanda if you see this you can close the issue. I don't have access to close this issue)

**Closed as completed** 2021-07-30 16:48 UTC

**Comment by Manderikoo** [comment] 2021-07-31 08:26
Thank you to both @skadefro and @kensoh so helping me solve this issue!
